// packages/create-electron-prokit/template-vue-ts/src/render/App.vue
<script setup lang="ts">
import { sendMsgToMain } from 'electron-prokit';
import HelloWorld from './components/HelloWorld.vue'
function openUrl() {
  sendMsgToMain({
    key: 'openUrl',
    data: {
      url: 'https://xutaotaotao.github.io/electron-prokit/'
    }
  })
}
</script>

<template>
  <div @click="openUrl">
    <img src="./assets/logo.svg" className="logo" alt="Vite logo" />
  </div>
  <HelloWorld msg="A vite + vue + electron template with electron-prokit." />
</template>

<style scoped>
.logo {
  height: 12em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}

.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}

.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// packages/create-electron-prokit/template-react-ts/src/render/App.tsx
import { useState } from 'react'
import Logo from './assets/logo.svg'
import { sendMsgToMain } from 'electron-prokit'
import './App.css'

function App() {
  const [count, setCount] = useState(0)

  return (
    <>
      <div onClick={() => sendMsgToMain({
        key:'openUrl',
        data: {
          url:'https://xutaotaotao.github.io/electron-prokit/'
        }
      })}>
          <img src={Logo} className="logo" alt="Vite logo" />
      </div>
      <p>A vite + react + electron template with electron-prokit.</p>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the logo to learn more
      </p>
    </>
  )
}

export default App
